// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtAE5Y9ZSrAXkoy0on8SAeQt2zcUwCqXU',
    appId: '1:6090418779:android:3dc936aaadf836c02fed7e',
    messagingSenderId: '6090418779',
    projectId: 'suivante-chat-app',
    storageBucket: 'suivante-chat-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXWm5Ay8yFsSeaU-Wl_pRwflhRy0MXZkQ',
    appId: '1:6090418779:ios:0252ff0c05c69de92fed7e',
    messagingSenderId: '6090418779',
    projectId: 'suivante-chat-app',
    storageBucket: 'suivante-chat-app.appspot.com',
    androidClientId:
        '6090418779-2b1opk1ualtgfile8v40vm3r3lvg1skh.apps.googleusercontent.com',
    iosClientId:
        '6090418779-2utqrsf89r4a8dqn1huel8clv6hsbhbe.apps.googleusercontent.com',
    iosBundleId: 'com.suivantec.suivanteChatApp',
  );
}
